const state = {
    active_tab: 'left',
    homeList: [],
    frontVersion: {},
    avatarUrl: '',
    nickName: '微信用户',
    getPhoneNumber: false,
    userInfo: {},
    userNFTAll: [],
    userCreateTimes: [],
    nftInfo: {},
    userCoupons: [],
    NFTMaterial: [],
    NFTTab: {},
    uuid: '',
    displayData: [],
    displayPagination: {},
    couponPagination: {},
    auth:false,
    phoneIsValidate: false,
    addressList:[],
    allArea: [],
    addrList:[],
    addrPagination:{},
    userIdAddress:{},
    myNftTradeList:[],
    displayNFT:{},
    identityType:0,
    codeCountDown:60,
    codeTimer:null,
    showSendBtn: true,
    isAppHide:false,
    teaList: [],
    selectFieldID: '',
    seletedAddr: null,
    orderList: [],
    giveOrder: null,
    orderPayInfo: null,
    receiveOrder: null
}

export default state